apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment%s
  labels:
    app: nginx%s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx%s
  template:
    metadata:
      labels:
        app: nginx%s
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service%s
  labels:
    app: nginx%s
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: %s
  selector:
    app: nginx%s